# Generated by Django 4.0.5 on 2022-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_misdatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisMascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
